language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "7.0"
  - "7.1"

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - travis_retry php vendor/bin/coveralls -v
